spring:
  datasource:
    url: jdbc:mysql://mysql:3306/medi_mate
    password: 123456
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
logging:
  level:
    root: warn